.TH "variants Directory Reference" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variants Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBproblem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproblem\&.h\fP"
.br
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.in -1c
