.TH "methods/analytical.h" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/analytical.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'method\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalytical\fP"
.br
.RI "\fIAn \fBAnalytical\fP class to compute the solution with standard procedures 
.br
 The implementation is derived from the \fBMethod\fP Object\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
