.TH "methods/implicit/crank_nicolson.h" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/implicit/crank_nicolson.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'implicit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrankNicolson\fP"
.br
.RI "\fIA \fBCrankNicolson\fP method class that contains a r vector builder\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
