.TH "DufortFrankel" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DufortFrankel \- A \fBDufortFrankel\fP method class that contains an iteration builder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dufort_frankel\&.h>\fP
.PP
Inherits \fBExplicit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDufortFrankel\fP (\fBProblem\fP \fBproblem\fP)"
.br
.RI "\fIDefault constructor\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVector\fP \fBbuild_iteration\fP (\fBVector\fP current_step, \fBVector\fP previous_step)"
.br
.RI "\fINormal protected method\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBDufortFrankel\fP method class that contains an iteration builder\&. 


.br
 This builder is used to calculate a solution using the Dufort-Frankel mathod\&.
.PP
The \fBDufortFrankel\fP class provides: 
.br
-a basic constructor for creating a \fBDufortFrankel\fP method object\&. 
.br
-a method to compute a solution of the current iteration 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DufortFrankel::DufortFrankel (\fBProblem\fP problem)"

.PP
Default constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBVector\fP DufortFrankel::build_iteration (\fBVector\fP current_step, \fBVector\fP previous_step)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Normal protected method\&. Calculate a next time step solution requiring a previous time step and a current time step solution\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcurrent_step\fP A vector representing the current time step solution\&. 
.br
\fIprevious_step\fP A vector representing the previous time step solution\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBVector\fP\&. The computed solution\&. 
.RE
.PP

.PP
Implements \fBExplicit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
