.TH "methods/explicit/dufort_frankel.cpp" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/explicit/dufort_frankel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dufort_frankel\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
