.TH "methods/explicit/dufort_frankel.h" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/explicit/dufort_frankel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'explicit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDufortFrankel\fP"
.br
.RI "\fIA \fBDufortFrankel\fP method class that contains an iteration builder\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
