.TH "methods/explicit/explicit.cpp" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/explicit/explicit.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'explicit\&.h'\fP
.br
\fC#include 'forward_t_central_s\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
