.TH "methods/explicit/explicit.h" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/explicit/explicit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./method\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExplicit\fP"
.br
.RI "\fIAn explicit method class that contains default methods that only explicit methods use 
.br
 The implementation is derived from the \fBMethod\fP class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
