.TH "io/iomanager.h" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io/iomanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./libs/gnuplot\-iostream\&.h'\fP
.br
\fC#include '\&.\&./methods/method\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIOManager\fP"
.br
.RI "\fIAn input/output manager class to handle plot exportations and future implementations of input handling\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
