.TH "Laasonen" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Laasonen \- A \fBLaasonen\fP method class that contains a r vector builder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <laasonen\&.h>\fP
.PP
Inherits \fBImplicit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaasonen\fP (\fBProblem\fP \fBproblem\fP)"
.br
.RI "\fIDefault constructor\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVector\fP \fBbuild_r\fP (\fBVector\fP previous_step)"
.br
.RI "\fINormal protected method\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBLaasonen\fP method class that contains a r vector builder\&. 


.br
 This builder is used is used to calculate the r vector in A\&.x = r linear equation system\&.
.PP
The \fBLaasonen\fP class provides: 
.br
-a basic constructor for creating a \fBLaasonen\fP method object\&. 
.br
-a method to compute the r vector\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Laasonen::Laasonen (\fBProblem\fP problem)"

.PP
Default constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBVector\fP Laasonen::build_r (\fBVector\fP previous_step)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Normal protected method\&. get the number of rows 
.PP
\fBParameters:\fP
.RS 4
\fIprevious_step\fP \fBVector\fP representing the solution of the previous time step\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBVector\fP\&. r vector to be used in A\&.x = r 
.RE
.PP

.PP
Implements \fBImplicit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
