.TH "main.cpp" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'methods/analytical\&.h'\fP
.br
\fC#include 'methods/explicit/dufort_frankel\&.h'\fP
.br
\fC#include 'methods/explicit/richardson\&.h'\fP
.br
\fC#include 'methods/implicit/laasonen\&.h'\fP
.br
\fC#include 'methods/implicit/crank_nicolson\&.h'\fP
.br
\fC#include 'io/iomanager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
