.TH "grid/matrix.cpp" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grid/matrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matrix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBMatrix\fP &m)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBMatrix\fP &m)"
.br
.ti -1c
.RI "std::ifstream & \fBoperator>>\fP (std::ifstream &ifs, \fBMatrix\fP &m)"
.br
.ti -1c
.RI "std::ofstream & \fBoperator<<\fP (std::ofstream &ofs, const \fBMatrix\fP &m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBMatrix\fP & m)"
Display output if matrix has size user will be asked to input only matrix values if matrix was not initialized user can choose matrix size and input it values 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::ifstream& ifs, Matrix& m)\fP 
.PP
\fBoperator>>(std::istream& is, Matrix& m)\fP 
.PP
\fBoperator<<(std::ostream& os, const Matrix& m)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream&\&. The ostream object 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIos\fP Display output stream 
.br
\fIm\fP \fBMatrix\fP to read from 
.RE
.PP

.SS "std::ofstream& operator<< (std::ofstream & ofs, const \fBMatrix\fP & m)"
File output the file output operator is compatible with file input operator, ie\&. everything written can be read later\&. 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::ifstream& ifs, Matrix& m)\fP 
.PP
\fBoperator<<(std::ofstream& ofs, const Matrix& m)\fP 
.PP
\fBoperator>>(std::istream& is, Matrix& m)\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::invalid_argument\fP ('file read error - negative matrix size'); 
.RE
.PP
\fBReturns:\fP
.RS 4
std::ofstream&\&. The ofstream object 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBMatrix\fP to read from 
.RE
.PP

.SS "std::istream& operator>> (std::istream & is, \fBMatrix\fP & m)"
Keyboard input if matrix has size user will be asked to input only matrix values if matrix was not initialized user can choose matrix size and input it values 
.PP
\fBSee also:\fP
.RS 4
\fBoperator<<(std::ofstream& ofs, const Matrix& m)\fP 
.PP
\fBoperator>>(std::istream& is, Matrix& m)\fP 
.PP
\fBoperator<<(std::ostream& os, const Matrix& m)\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::invalid_argument\fP ('read error - negative matrix size'); 
.RE
.PP
\fBReturns:\fP
.RS 4
std::istream&\&. The istream object 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIis\fP Keyboard input stream 
.br
\fIm\fP \fBMatrix\fP to write into 
.RE
.PP

.SS "std::ifstream& operator>> (std::ifstream & ifs, \fBMatrix\fP & m)"
File input the file output operator is compatible with file input operator, ie\&. everything written can be read later\&. 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::ifstream& ifs, Matrix& m)\fP 
.PP
\fBoperator<<(std::ofstream& ofs, const Matrix& m)\fP 
.PP
\fBoperator<<(std::ostream& os, const Matrix& m)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::ifstream&\&. The ifstream object 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIifs\fP Input file stream with opened matrix file 
.br
\fIm\fP \fBMatrix\fP to write into 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
