.TH "grid/matrix.h" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grid/matrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'vector\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.RI "\fIA matrix class for data storage of a 2D array of doubles 
.br
 The implementation is derived from the standard container vector std::vector 
.br
 We use private inheritance to base our vector upon the library version whilst  usto expose only those base class functions we wish to use - in this  the array access operator []\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
