.TH "methods/method.h" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
methods/method.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./variants/problem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMethod\fP"
.br
.RI "\fIA \fBMethod\fP class to structure information used to solve the problem\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
