.TH "variants/problem.h" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variants/problem.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./variants/utils\&.h'\fP
.br
\fC#include '\&.\&./grid/matrix\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProblem\fP"
.br
.RI "\fIA \fBProblem\fP class to structure relevant information related with the problem\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
