.TH "variants/utils.h" 3 "Mon Nov 6 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variants/utils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBDELTA_T\fP = 0\&.01"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBDELTA_X\fP = 0\&.05"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const std::vector< double > \fBDELTA_T_LASSONEN\fP = {0\&.01, 0\&.025, 0\&.05, 0\&.1}"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBDIFUSIVITY\fP = 0\&.1"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBTHICKNESS\fP = 1\&.0"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBTIMELIMIT\fP = 0\&.5"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBSURFACE_TEMPERATURE\fP = 300\&.0"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBINITIAL_TEMPERATURE\fP = 100\&.0"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const double \fBNUMBER_TIME_STEPS\fP = 6\&.0"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const unsigned int \fBNUMBER_OF_EXPANSIONS\fP = 20"
.br
.RI "\fIMacro unsigned int\&. \fP"
.ti -1c
.RI "const double \fBPI\fP = std::atan(1) * 4"
.br
.RI "\fIMacro double\&. \fP"
.ti -1c
.RI "const std::string \fBOUTPUT_PATH\fP = '\&.\&./outputs'"
.br
.RI "\fIMacro string\&. \fP"
.ti -1c
.RI "const std::string \fBFORWARD_TIME_CENTRAL_SPACE\fP = 'Forward Time Central Space'"
.br
.RI "\fIMacro string\&. \fP"
.ti -1c
.RI "const std::string \fBRICHARDSON\fP = 'Richardson'"
.br
.RI "\fIMacro string\&. \fP"
.ti -1c
.RI "const std::string \fBDUFORT_FRANKEL\fP = 'DuFort\-Frankel'"
.br
.RI "\fIMacro string\&. \fP"
.ti -1c
.RI "const std::string \fBLAASONEN\fP = 'Laasonen'"
.br
.RI "\fIMacro string\&. \fP"
.ti -1c
.RI "const std::string \fBCRANK_NICHOLSON\fP = 'Crank\-Nicholson'"
.br
.RI "\fIMacro string\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const std::string CRANK_NICHOLSON = 'Crank\-Nicholson'"

.PP
Macro string\&. Crank-Nicholson method name\&. 
.SS "const double DELTA_T = 0\&.01"

.PP
Macro double\&. The default time step\&. 
.SS "const std::vector<double> DELTA_T_LASSONEN = {0\&.01, 0\&.025, 0\&.05, 0\&.1}"

.PP
Macro double\&. Time steps to study in \fBLaasonen\fP \fBImplicit\fP Scheme\&. 
.SS "const double DELTA_X = 0\&.05"

.PP
Macro double\&. The default space step\&. 
.SS "const double DIFUSIVITY = 0\&.1"

.PP
Macro double\&. The default value of difusivity\&. 
.SS "const std::string DUFORT_FRANKEL = 'DuFort\-Frankel'"

.PP
Macro string\&. DuFort-Frankel method name\&. 
.SS "const std::string FORWARD_TIME_CENTRAL_SPACE = 'Forward Time Central Space'"

.PP
Macro string\&. Forward in Time and Central in Space method name\&. 
.SS "const double INITIAL_TEMPERATURE = 100\&.0"

.PP
Macro double\&. The default initial temperature\&. 
.SS "const std::string LAASONEN = 'Laasonen'"

.PP
Macro string\&. \fBLaasonen\fP method name\&. 
.SS "const unsigned int NUMBER_OF_EXPANSIONS = 20"

.PP
Macro unsigned int\&. Number of expansions to calculate the analytical solution sum expansion\&. 
.SS "const double NUMBER_TIME_STEPS = 6\&.0"

.PP
Macro double\&. The default limit of time steps\&. 0, 0\&.1, 0\&.2, 0\&.3, 0\&.4, 0\&.5 
.SS "const std::string OUTPUT_PATH = '\&.\&./outputs'"

.PP
Macro string\&. Default outputs path\&. 
.SS "const double PI = std::atan(1) * 4"

.PP
Macro double\&. Approximated value of PI\&. 
.SS "const std::string RICHARDSON = 'Richardson'"

.PP
Macro string\&. \fBRichardson\fP method name\&. 
.SS "const double SURFACE_TEMPERATURE = 300\&.0"

.PP
Macro double\&. The default surface temperature\&. 
.SS "const double THICKNESS = 1\&.0"

.PP
Macro double\&. The default value of thickness\&. 
.SS "const double TIMELIMIT = 0\&.5"

.PP
Macro double\&. The default value of time limit\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
