.TH "grid/vector.cpp" 3 "Sun Dec 10 2017" "Heat conduction equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grid/vector.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBVector\fP &v)"
.br
.ti -1c
.RI "std::ifstream & \fBoperator>>\fP (std::ifstream &ifs, \fBVector\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBVector\fP &v)"
.br
.ti -1c
.RI "std::ofstream & \fBoperator<<\fP (std::ofstream &ofs, const \fBVector\fP &v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBVector\fP & v)"
Display output\&. 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::istream& is, Vector& v)\fP 
.PP
\fBoperator>>(std::ifstream& ifs, Vector& v)\fP 
.PP
\fBoperator<<(std::ofstream& ofs, const Vector& v)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream&\&. the output stream object os 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIos\fP output file stream 
.br
\fIv\fP vector to read from 
.RE
.PP

.SS "std::ofstream& operator<< (std::ofstream & ofs, const \fBVector\fP & v)"
File output\&. the file output operator is compatible with file input operator, ie\&. everything written can be read later\&. 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::istream& is, Vector& v)\fP 
.PP
\fBoperator>>(std::ifstream& ifs, Vector& v)\fP 
.PP
\fBoperator<<(std::ostream& os, const Vector& v)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::ofstream&\&. the output ofstream object ofs 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIofs\fP outputfile stream\&. With opened file 
.br
\fIv\fP \fBVector\fP&\&. vector to read from 
.RE
.PP

.SS "std::istream& operator>> (std::istream & is, \fBVector\fP & v)"
Keyboard input if vector has size user will be asked to input only vector values if vector was not initialized user can choose vector size and input it values 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::ifstream& ifs, Vector& v)\fP 
.PP
\fBoperator<<(std::ostream& os, const Vector& v)\fP 
.PP
\fBoperator<<(std::ofstream& ofs, const Vector& v)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::istream&\&. the input stream object is 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::invalid_argument\fP ('read error - negative vector size'); 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIis\fP keyboard input straem\&. For user input 
.br
\fIv\fP \fBVector\fP&\&. vector to write to 
.RE
.PP

.SS "std::ifstream& operator>> (std::ifstream & ifs, \fBVector\fP & v)"
File input the file output operator is compatible with file input operator, ie\&. everything written can be read later\&. 
.PP
\fBSee also:\fP
.RS 4
\fBoperator>>(std::istream& is, Vector& v)\fP 
.PP
\fBoperator<<(std::ostream& os, const Vector& v)\fP 
.PP
\fBoperator<<(std::ofstream& ofs, const Vector& v)\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
ifstream&\&. the input ifstream object ifs 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::invalid_argument\fP ('file read error - negative vector size'); 
.RE
.PP

.PP
\fBParameters:\fP
.RS 4
\fIifs\fP input file straem\&. With opened matrix file 
.br
\fIv\fP \fBVector\fP&\&. vector to write to 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Heat conduction equation from the source code\&.
