all: *.cpp
	g++ -std=c++11 *.cpp */*.cpp */*/*.cpp -o assignment -lboost_iostreams -lboost_system -lboost_filesystem
install:
	sudo apt-get install libboost-iostreams-dev libboost-system-dev libboost-filesystem-dev
